// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbC7dp9ibvPfkt5bAoS5WwPdBxw6m7EKA',
    appId: '1:965626965450:web:e0cb0bc14e74fca39cf333',
    messagingSenderId: '965626965450',
    projectId: 'jhol-jhal-879a1',
    authDomain: 'jhol-jhal-879a1.firebaseapp.com',
    storageBucket: 'jhol-jhal-879a1.firebasestorage.app',
    measurementId: 'G-96JZB5EC81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg53gwFDw84LkGuEwww3_xvC9SonpOniE',
    appId: '1:965626965450:android:540e57a8c784c2d59cf333',
    messagingSenderId: '965626965450',
    projectId: 'jhol-jhal-879a1',
    storageBucket: 'jhol-jhal-879a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNguMRX7pyZFj29GPcNNfmKCxoaDUFkNs',
    appId: '1:965626965450:ios:a342090558e8a2de9cf333',
    messagingSenderId: '965626965450',
    projectId: 'jhol-jhal-879a1',
    storageBucket: 'jhol-jhal-879a1.firebasestorage.app',
  iosBundleId: 'com.jholjhal.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNguMRX7pyZFj29GPcNNfmKCxoaDUFkNs',
    appId: '1:965626965450:ios:a342090558e8a2de9cf333',
    messagingSenderId: '965626965450',
    projectId: 'jhol-jhal-879a1',
    storageBucket: 'jhol-jhal-879a1.firebasestorage.app',
  iosBundleId: 'com.jholjhal.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbC7dp9ibvPfkt5bAoS5WwPdBxw6m7EKA',
    appId: '1:965626965450:web:25d8fd2dc717970b9cf333',
    messagingSenderId: '965626965450',
    projectId: 'jhol-jhal-879a1',
    authDomain: 'jhol-jhal-879a1.firebaseapp.com',
    storageBucket: 'jhol-jhal-879a1.firebasestorage.app',
    measurementId: 'G-RM71SKC73D',
  );
}
